//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> CardExpirationDate { get; set; }
        public string SecurityCode { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
