//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public int Id { get; set; }
        public Nullable<int> IdAccount { get; set; }
        public Nullable<int> IdAccountLevel { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AccountLevel AccountLevel { get; set; }
    }
}
