//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VideoInfo()
        {
            this.WatchHistories = new HashSet<WatchHistory>();
            this.Accounts = new HashSet<Account>();
            this.VideoGenres = new HashSet<VideoGenre>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Origin { get; set; }
        public string Director { get; set; }
        public string Path { get; set; }
        public string Image { get; set; }
        public string ImageDetail { get; set; }
        public string VideoDescription { get; set; }
        public string Actor { get; set; }
        public Nullable<int> HotLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WatchHistory> WatchHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoGenre> VideoGenres { get; set; }
    }
}
