//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatchHistory
    {
        public int IdAccount { get; set; }
        public int IdVideo { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual VideoInfo VideoInfo { get; set; }
    }
}
